### ISSUE TITLE
Stepper not running

### ISSUE THREAD

**Issue by klchin66** [thomast777/grbl32#1]
Hi,

I had try your codes. I do faced some problem. My board is
407ZGT 168Mhz, 8Mhz Chinese general board.  

The motion was correct if do jogging, when send the g-code
it receive the code and buffered in the queue, but it only move little
steps then it stopped completely,  No idea locked in which loop code,
I did stop at SysTick to check the sys.state or sys.suspend these 2 
status was good '0'.

I did noticed TIM5_IRQHandler and TIM6_IRQHandler did triggering 
for a while when using send gcode, I think only the 1st packet gcode. 

Any idea which portion of code I should check in to find the actual cause.
Is it because of the timing issue or wrong PIN?

Also which part of the code I shell change the Clock speed, since 
your board using 200Mhz.   I did changed the SystemClock_Config
for my board.
        RCC_OscInitStruct.PLL.PLLM    = 25;
        RCC_OscInitStruct.PLL.PLLN    = 360;
        RCC_OscInitStruct.PLL.PLLP    = RCC_PLLP_DIV2;
        RCC_OscInitStruct.PLL.PLLQ    = 7;

FYI, I did tried out Schildkroet/GRBL-Advanced code,  it works on  my board.

TQVM
KL

**Comment by qiwalker** [comment]
hi can u send me tutorial how to flash this firmware to STM32 board ?
this is my first time use STM32 board.
