### ISSUE TITLE
Compiled STM32CubeIDE F13 on blue pill SERIAL USB not detected.

### ISSUE THREAD

**Issue by AxelGUILLAUMET** [thomast777/grbl32#11]
Hi!

This actualized STM32-GRBL project looks to be very good but I have some issues...

I recompiled the project successfully with STM32CubeIDE, I load the firmware on the blue pill and there is nothing detected by the PC.

I had in the past the same issue and iw was due to a bad clone of the STM32F103.

But this time it can't be the STM32F103 I have on my blue pill because when I compile another firmware, it works (This one -> https://github.com/ewidance/grbl-usbcnc-stm32) 

I send you there all the specs of my hardware...

The .elf file of the F13 compiled on STM32CubeIDE

And the working .elf file I compiled form https://github.com/ewidance/grbl-usbcnc-stm32 which is working

I think it can be  an USB activation issue in the source code but I don't found nothing clear about that...

![BluePill Specs](https://user-images.githubusercontent.com/47301337/81128254-5103ca00-8f06-11ea-8cdd-8e739ff1a570.JPG)

![BluePill](https://user-images.githubusercontent.com/47301337/81129495-21ef5780-8f0a-11ea-8c3d-803a9d1a29b2.jpg)

[STM32 compiled firmwares.zip](https://github.com/thomast777/grbl32/files/4584382/STM32.compiled.firmwares.zip)

**Comment by mwshakoor154** [comment]
i think this only supports USART, no usb support.
I also tested, usb not detected.
as far as my understandings after checking hardware notes, it clearly shows PB6 = Tx, PB7= RX.
https://github.com/thomast777/grbl32/wiki/Hardware-Notes
I have not tested using USART but i guess it will work.

**Comment by mwshakoor154** [comment]
Today I checked f13.
UART is working
set baud rate to 921600

**Comment by AxelGUILLAUMET** [comment]
OK thanks a lot, I confirm this, if you are looking at this page which is the page of the oficial hardware of this firmware, https://shop.tomsrobotics.com/product/f13-bundles you can see clearly the 12Mhz crystal, used by the CH340 USB to Serial chip. 

Here in the F16 https://shop.tomsrobotics.com/product/f16-bundles/ you can see clearly the CH340 chip itself.

Tomorrow I will make a test with real hardware. I plan to use it with LightBurn and a CO2 Synrad RF laser of 40 Watts.

**Comment by AxelGUILLAUMET** [comment]
OK USART confirmed and lightburn GRBL compatibility is OK

![0ba2e836-397d-4ecf-b564-0a54804e5626](https://user-images.githubusercontent.com/47301337/82524218-008a9000-9af4-11ea-9833-80c6e7b21dd3.jpg)

![dcc01a75-23fa-404a-905d-b473528978a9](https://user-images.githubusercontent.com/47301337/82524222-02545380-9af4-11ea-80b4-bfdb6622e8ec.jpg)

I modded for the moment src/usart.c to change the speed to 115200bps due to the FT232 module is a counterfeit and is only limited to 115200 Max. But to test and validate this GRBL port on STM32 platform it is the best.

Thanks and regards.
